{
 "title": "Postgres",
 "description": "Dashboard for Postgres",
 "tags": [ "postgres" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(postgres_exporter_build_info, namespace)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(postgres_exporter_build_info{namespace=~\"$namespace\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Database Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Database Size",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{job=~\"$job\", namespace=~\"$namespace\"}) by (datname)",
     "legendFormat": "{{ datname }}",
     "query": "sum(pg_database_size_bytes{job=~\"$job\", namespace=~\"$namespace\"}) by (datname)"
    }
   ]
  },
  {
   "title": "Database Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{job=~\"$job\", namespace=~\"$namespace\"}) by (datname)",
     "legendFormat": "{{ datname }}",
     "query": "sum(pg_database_size_bytes{job=~\"$job\", namespace=~\"$namespace\"}) by (datname)"
    }
   ]
  },
  {
   "title": "Locks count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_locks_count{job=~\"$job\", namespace=~\"$namespace\"}) by (datname, mode)",
     "legendFormat": "{{ datname }}",
     "query": "sum(pg_locks_count{job=~\"$job\", namespace=~\"$namespace\"}) by (datname, mode)"
    }
   ]
  },
  {
   "title": "Number of backends connected",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends{job=~\"$job\", namespace=~\"$namespace\", datname!=\"\"}) by (datname)",
     "legendFormat": "{{ datname }}",
     "query": "sum(pg_stat_database_numbackends{job=~\"$job\", namespace=~\"$namespace\", datname!=\"\"}) by (datname)"
    }
   ]
  },
  { "title": "Activity count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"active\"}) by (datname)",
     "legendFormat": "{{ datname }}",
     "query": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"active\"}) by (datname)"
    }
   ]
  },
  {
   "title": "Disabled",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"disabled\"}) by (datname)",
     "legendFormat": "{{ datname }}",
     "query": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"disabled\"}) by (datname)"
    }
   ]
  },
  {
   "title": "Fastpath function call",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"fastpath function call\"}) by (datname)",
     "legendFormat": "{{ datname }}",
     "query": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"fastpath function call\"}) by (datname)"
    }
   ]
  },
  {
   "title": "Idle",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"idle\"}) by (datname)",
     "legendFormat": "{{ datname }}",
     "query": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"idle\"}) by (datname)"
    }
   ]
  },
  {
   "title": "Idle in transaction",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"idle in transaction\"}) by (datname)",
     "legendFormat": "{{ datname }}",
     "query": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"idle in transaction\"}) by (datname)"
    }
   ]
  },
  {
   "title": "Idle in transaction (aborted)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"idle in transaction (aborted)\"}) by (datname)",
     "legendFormat": "{{ datname }}",
     "query": "sum(pg_stat_activity_count{job=~\"$job\", namespace=~\"$namespace\", state=\"idle in transaction (aborted)\"}) by (datname)"
    }
   ]
  },
  {
   "title": "Resource Usage (postgres-exporter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod }}",
     "query": "process_open_fds{job=~\"$job\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}",
     "query": "rate(process_cpu_seconds_total{job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod }}",
     "query": "process_resident_memory_bytes{job=~\"$job\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Stack Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_stack_sys_bytes{job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "sys",
     "query": "avg(go_memstats_stack_sys_bytes{job=~\"$job\", namespace=~\"$namespace\"})"
    },
    {
     "expr": "avg(go_memstats_stack_inuse_bytes{job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "inuse",
     "query": "avg(go_memstats_stack_inuse_bytes{job=~\"$job\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_heap_sys_bytes{job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "sys",
     "query": "avg(go_memstats_heap_sys_bytes{job=~\"$job\", namespace=~\"$namespace\"})"
    },
    {
     "expr": "avg(go_memstats_heap_idle_bytes{job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "idle",
     "query": "avg(go_memstats_heap_idle_bytes{job=~\"$job\", namespace=~\"$namespace\"})"
    },
    {
     "expr": "avg(go_memstats_heap_released_bytes{job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "released",
     "query": "avg(go_memstats_heap_released_bytes{job=~\"$job\", namespace=~\"$namespace\"})"
    },
    {
     "expr": "avg(go_memstats_next_gc_bytes{job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "next_gc",
     "query": "avg(go_memstats_next_gc_bytes{job=~\"$job\", namespace=~\"$namespace\"})"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "inuse",
     "query": "avg(go_memstats_heap_inuse_bytes{job=~\"$job\", namespace=~\"$namespace\"})"
    },
    {
     "expr": "avg(go_memstats_heap_alloc_bytes{job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "alloc",
     "query": "avg(go_memstats_heap_alloc_bytes{job=~\"$job\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod }}",
     "query": "go_goroutines{job=~\"$job\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Go Alloc Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}",
     "query": "rate(go_memstats_alloc_bytes_total{job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Go Alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod }}",
     "query": "go_memstats_alloc_bytes{job=~\"$job\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Go GC Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}",
     "query": "rate(go_gc_duration_seconds_count{job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Go GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}",
     "query": "rate(go_gc_duration_seconds_sum{job=~\"$job\", namespace=~\"$namespace\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_threads{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "{{ pod }}",
     "query": "go_threads{job=~\"$job\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_heap_objects{job=~\"$job\", namespace=~\"$namespace\"})",
     "legendFormat": "objects",
     "query": "avg(go_memstats_heap_objects{job=~\"$job\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Go Info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "go_info{job=~\"$job\", namespace=~\"$namespace\"}",
     "legendFormat": "{{ version }}",
     "query": "go_info{job=~\"$job\", namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Last GC time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_last_gc_time_seconds{job=~\"$job\", namespace=~\"$namespace\"} * 1000",
     "query": "go_memstats_last_gc_time_seconds{job=~\"$job\", namespace=~\"$namespace\"} * 1000"
    }
   ]
  }
 ]
}