version: 3

tasks:
  generate-all:
    cmds:
      - poetry run python postgres.py
      - poetry run python traefik.py

  generate:
    cmds:
      # - go run . {{ .CLI_ARGS }}
      - poetry run python {{ .CLI_ARGS }}.py
