{
 "title": "Traefik",
 "description": "Dashboard for Traefik",
 "tags": [ "traefik" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(traefik_config_last_reload_success, namespace)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(traefik_config_last_reload_success{namespace=~\"$namespace\"}, instance)"
   },
   {
    "name": "entrypoint",
    "label": "Entrypoint",
    "query": "label_values(traefik_entrypoint_open_connections{namespace=~\"$namespace\"}, entrypoint)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(traefik_service_open_connections{namespace=~\"$namespace\"}, service)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__range]))",
     "query": "sum(increase(traefik_service_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Request Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__range]))",
     "query": "sum(increase(traefik_service_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Response Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__range]))",
     "query": "sum(increase(traefik_service_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Config reloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_config_reloads_total{namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]))",
     "query": "sum(increase(traefik_config_reloads_total{namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Config reloads failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_config_reloads_failure_total{namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]))",
     "query": "sum(increase(traefik_config_reloads_failure_total{namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Last successful config reload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(traefik_config_last_reload_success{namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]) * 1000",
     "query": "max(traefik_config_last_reload_success{namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]) * 1000"
    }
   ]
  },
  {
   "title": "Last failed config reload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(traefik_config_last_reload_failure{namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]) * 1000",
     "query": "max(traefik_config_last_reload_failure{namespace=~\"$namespace\", instance=~\"$instance\"}[$__range]) * 1000"
    }
   ]
  },
  { "title": "Entrypoint Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Open connections by protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__interval]) by (entrypoint, protocol)",
     "legendFormat": "{{ entrypoint }} - {{ protocol }}",
     "query": "sum(traefik_entrypoint_open_connections{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__interval]) by (entrypoint, protocol)"
    }
   ]
  },
  {
   "title": "Open connections by method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__interval]) by (entrypoint, method)",
     "legendFormat": "{{ entrypoint }} - {{ method }}",
     "query": "sum(traefik_entrypoint_open_connections{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__interval]) by (entrypoint, method)"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__interval])) by (entrypoint)",
     "legendFormat": "{{ entrypoint }}",
     "query": "sum(increase(traefik_entrypoint_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__interval])) by (entrypoint)"
    }
   ]
  },
  {
   "title": "Request Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__interval])) by (entrypoint)",
     "legendFormat": "{{ entrypoint }}",
     "query": "sum(increase(traefik_entrypoint_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__interval])) by (entrypoint)"
    }
   ]
  },
  {
   "title": "Response Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__interval])) by (entrypoint)",
     "legendFormat": "{{ entrypoint }}",
     "query": "sum(increase(traefik_entrypoint_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__interval])) by (entrypoint)"
    }
   ]
  },
  {
   "title": "Avg request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(traefik_entrypoint_request_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__rate_interval])) by (entrypoint) / sum(rate(traefik_entrypoint_request_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__rate_interval])) by (entrypoint), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ entrypoint }}",
     "query": "label_replace(sum(rate(traefik_entrypoint_request_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__rate_interval])) by (entrypoint) / sum(rate(traefik_entrypoint_request_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\", entrypoint=~\"$entrypoint\"}[$__rate_interval])) by (entrypoint), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  { "title": "Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Open connections by service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(traefik_service_open_connections{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval]) by (service), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ service }}",
     "query": "label_replace(sum(traefik_service_open_connections{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval]) by (service), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Open connections by protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(traefik_service_open_connections{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval]) by (protocol), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ protocol }}",
     "query": "label_replace(sum(traefik_service_open_connections{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval]) by (protocol), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Open connections by method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(traefik_service_open_connections{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval]) by (method), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ method }}",
     "query": "label_replace(sum(traefik_service_open_connections{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval]) by (method), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Request Count by service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (service), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ service }}",
     "query": "label_replace(sum(increase(traefik_service_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (service), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Request Bytes by service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (service), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ service }}",
     "query": "label_replace(sum(increase(traefik_service_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (service), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Response Bytes by service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (service), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ service }}",
     "query": "label_replace(sum(increase(traefik_service_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (service), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Avg request duration by service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(traefik_service_request_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (service) / sum(rate(traefik_service_request_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (service), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ service }}",
     "query": "label_replace(sum(rate(traefik_service_request_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (service) / sum(rate(traefik_service_request_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (service), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Request Count by protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (protocol), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ protocol }}",
     "query": "label_replace(sum(increase(traefik_service_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (protocol), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Request Bytes by protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (protocol), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ protocol }}",
     "query": "label_replace(sum(increase(traefik_service_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (protocol), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Response Bytes by protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (protocol), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ protocol }}",
     "query": "label_replace(sum(increase(traefik_service_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (protocol), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Avg request duration by protocol",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(traefik_service_request_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (protocol) / sum(rate(traefik_service_request_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (protocol), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ protocol }}",
     "query": "label_replace(sum(rate(traefik_service_request_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (protocol) / sum(rate(traefik_service_request_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (protocol), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Request Count by method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (method), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ method }}",
     "query": "label_replace(sum(increase(traefik_service_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (method), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Request Bytes by method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (method), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ method }}",
     "query": "label_replace(sum(increase(traefik_service_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (method), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Response Bytes by method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (method), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ method }}",
     "query": "label_replace(sum(increase(traefik_service_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (method), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Avg request duration by method",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(traefik_service_request_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (method) / sum(rate(traefik_service_request_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (method), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ method }}",
     "query": "label_replace(sum(rate(traefik_service_request_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (method) / sum(rate(traefik_service_request_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (method), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Request Count by code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (code), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ code }}",
     "query": "label_replace(sum(increase(traefik_service_requests_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (code), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Request Bytes by code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (code), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ code }}",
     "query": "label_replace(sum(increase(traefik_service_requests_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (code), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Response Bytes by code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum(increase(traefik_service_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (code), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ code }}",
     "query": "label_replace(sum(increase(traefik_service_responses_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__interval])) by (code), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "Avg request duration by code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "label_replace(sum(rate(traefik_service_request_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (code) / sum(rate(traefik_service_request_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (code), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")",
     "legendFormat": "{{ code }}",
     "query": "label_replace(sum(rate(traefik_service_request_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (code) / sum(rate(traefik_service_request_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\", service=~\"$service\"}[$__rate_interval])) by (code), \"service\", \"$1\", \"service\", \"([^-]+-[^@]+)@.*\")"
    }
   ]
  },
  {
   "title": "TLS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "TLS requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_tls_total{namespace=~\"$namespace\", instance=~\"$instance\"}[$__interval])) by (service, tls_cipher, version)",
       "legendFormat": "{{ service }} {{ tls_cipher }} {{ version }}",
       "query": "sum(increase(traefik_service_requests_tls_total{namespace=~\"$namespace\", instance=~\"$instance\"}[$__interval])) by (service, tls_cipher, version)"
      }
     ]
    },
    {
     "title": "TLS certs expiration timestamp",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "max(traefik_tls_certs_not_after{namespace=~\"$namespace\", instance=~\"$instance\"}) by (cn, sans, serial) * 1000",
       "legendFormat": "{{ cn }} {{ sans }} {{ serial }}",
       "query": "max(traefik_tls_certs_not_after{namespace=~\"$namespace\", instance=~\"$instance\"}) by (cn, sans, serial) * 1000"
      }
     ]
    }
   ]
  },
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{ pod }}",
     "query": "process_open_fds{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}",
     "query": "rate(process_cpu_seconds_total{namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{ pod }}",
     "query": "process_resident_memory_bytes{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Stack Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_stack_sys_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "sys",
     "query": "avg(go_memstats_stack_sys_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})"
    },
    {
     "expr": "avg(go_memstats_stack_inuse_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "inuse",
     "query": "avg(go_memstats_stack_inuse_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_heap_sys_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "sys",
     "query": "avg(go_memstats_heap_sys_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})"
    },
    {
     "expr": "avg(go_memstats_heap_idle_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "idle",
     "query": "avg(go_memstats_heap_idle_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})"
    },
    {
     "expr": "avg(go_memstats_heap_released_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "released",
     "query": "avg(go_memstats_heap_released_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})"
    },
    {
     "expr": "avg(go_memstats_next_gc_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "next_gc",
     "query": "avg(go_memstats_next_gc_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "inuse",
     "query": "avg(go_memstats_heap_inuse_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})"
    },
    {
     "expr": "avg(go_memstats_heap_alloc_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})",
     "legendFormat": "alloc",
     "query": "avg(go_memstats_heap_alloc_bytes{namespace=~\"$namespace\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{ pod }}",
     "query": "go_goroutines{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Go Alloc Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}",
     "query": "rate(go_memstats_alloc_bytes_total{namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Go Alloc",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{ pod }}",
     "query": "go_memstats_alloc_bytes{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Go GC Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}",
     "query": "rate(go_gc_duration_seconds_count{namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Go GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ pod }}",
     "query": "rate(go_gc_duration_seconds_sum{namespace=~\"$namespace\", instance=~\"$instance\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_threads{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{ pod }}",
     "query": "go_threads{namespace=~\"$namespace\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(go_memstats_heap_objects{namespace=~\"$namespace\", instance=~\"$instance\"}) by (pod)",
     "legendFormat": "{{ pod }}",
     "query": "avg(go_memstats_heap_objects{namespace=~\"$namespace\", instance=~\"$instance\"}) by (pod)"
    }
   ]
  }
 ]
}