// https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/valueFormats/categories.ts (use id field)

export enum Unit {
  NONE = 'none', // Number
  STRING = 'string', // String
  SHORT = 'short', // short
  PERCENT = 'percent', // Percent (0-100)
  PERCENTUNIT = 'percentunit', // Percent (0.0-1.0)
  HUMIDITY = 'humidity', // Humidity (%H)
  DB = 'dB', // Decibel
  CANDELA = 'candela', // Candela (cd)
  HEX0X = 'hex0x', // Hexadecimal (0x)
  HEX = 'hex', // Hexadecimal
  SCI = 'sci', // Scientific notation
  LOCALE = 'locale', // Locale format
  PIXEL = 'pixel', // Pixels
  ACCMS2 = 'accMS2', // Meters/sec²
  ACCFS2 = 'accFS2', // Feet/sec²
  ACCG = 'accG', // G unit
  DEGREE = 'degree', // Degrees (°)
  RADIAN = 'radian', // Radians
  GRAD = 'grad', // Gradian
  ARCMIN = 'arcmin', // Arc Minutes
  ARCSEC = 'arcsec', // Arc Seconds
  AREAM2 = 'areaM2', // Square Meters (m²)
  AREAF2 = 'areaF2', // Square Feet (ft²)
  AREAMI2 = 'areaMI2', // Square Miles (mi²)
  ACRES = 'acres', // Acres (ac)
  HECTARES = 'hectares', // Hectares (ha)
  FLOPS = 'flops', // FLOP/s
  MFLOPS = 'mflops', // MFLOP/s
  GFLOPS = 'gflops', // GFLOP/s
  TFLOPS = 'tflops', // TFLOP/s
  PFLOPS = 'pflops', // PFLOP/s
  EFLOPS = 'eflops', // EFLOP/s
  ZFLOPS = 'zflops', // ZFLOP/s
  YFLOPS = 'yflops', // YFLOP/s
  PPM = 'ppm', // parts-per-million (ppm)
  CONPPB = 'conppb', // parts-per-billion (ppb)
  CONNGM3 = 'conngm3', // nanogram per cubic meter (ng/m³)
  CONNGNM3 = 'conngNm3', // nanogram per normal cubic meter (ng/Nm³)
  CONΜGM3 = 'conμgm3', // microgram per cubic meter (μg/m³)
  CONΜGNM3 = 'conμgNm3', // microgram per normal cubic meter (μg/Nm³)
  CONMGM3 = 'conmgm3', // milligram per cubic meter (mg/m³)
  CONMGNM3 = 'conmgNm3', // milligram per normal cubic meter (mg/Nm³)
  CONGM3 = 'congm3', // gram per cubic meter (g/m³)
  CONGNM3 = 'congNm3', // gram per normal cubic meter (g/Nm³)
  CONMGDL = 'conmgdL', // milligrams per decilitre (mg/dL)
  CONMMOLL = 'conmmolL', // millimoles per litre (mmol/L)
  CURRENCYUSD = 'currencyUSD', // Dollars ($)
  CURRENCYGBP = 'currencyGBP', // Pounds (£)
  CURRENCYEUR = 'currencyEUR', // Euro (€)
  CURRENCYJPY = 'currencyJPY', // Yen (¥)
  CURRENCYRUB = 'currencyRUB', // Rubles (₽)
  CURRENCYUAH = 'currencyUAH', // Hryvnias (₴)
  CURRENCYBRL = 'currencyBRL', // Real (R$)
  CURRENCYDKK = 'currencyDKK', // Danish Krone (kr)
  CURRENCYISK = 'currencyISK', // Icelandic Króna (kr)
  CURRENCYNOK = 'currencyNOK', // Norwegian Krone (kr)
  CURRENCYSEK = 'currencySEK', // Swedish Krona (kr)
  CURRENCYCZK = 'currencyCZK', // Czech koruna (czk)
  CURRENCYCHF = 'currencyCHF', // Swiss franc (CHF)
  CURRENCYPLN = 'currencyPLN', // Polish Złoty (PLN)
  CURRENCYBTC = 'currencyBTC', // Bitcoin (฿)
  CURRENCYMBTC = 'currencymBTC', // Milli Bitcoin (฿)
  CURRENCYΜBTC = 'currencyμBTC', // Micro Bitcoin (฿)
  CURRENCYZAR = 'currencyZAR', // South African Rand (R)
  CURRENCYINR = 'currencyINR', // Indian Rupee (₹)
  CURRENCYKRW = 'currencyKRW', // South Korean Won (₩)
  CURRENCYIDR = 'currencyIDR', // Indonesian Rupiah (Rp)
  CURRENCYPHP = 'currencyPHP', // Philippine Peso (PHP)
  CURRENCYVND = 'currencyVND', // Vietnamese Dong (VND)
  CURRENCYTRY = 'currencyTRY', // Turkish Lira (₺)
  CURRENCYMYR = 'currencyMYR', // Malaysian Ringgit (RM)
  CURRENCYXPF = 'currencyXPF', // CFP franc (XPF)
  BYTES_IEC = 'bytes', // bytes(IEC)
  BYTES_SI = 'decbytes', // bytes(SI)
  BITS_IEC = 'bits', // bits(IEC)
  BITS_SI = 'decbits', // bits(SI)
  KBYTES_IEC = 'kbytes', // kibibytes
  KBYTES_SI = 'deckbytes', // kilobytes
  MBYTES_IEC = 'mbytes', // mebibytes
  MBYTES_SI = 'decmbytes', // megabytes
  GBYTES_IEC = 'gbytes', // gibibytes
  GBYTES_SI = 'decgbytes', // gigabytes
  TBYTES_IEC = 'tbytes', // tebibytes
  TBYTES_SI = 'dectbytes', // terabytes
  PBYTES_IEC = 'pbytes', // pebibytes
  PBYTES_SI = 'decpbytes', // petabytes
  PPS = 'pps', // packets/sec
  BYTES_PER_SEC_IEC = 'binBps', // bytes/sec(IEC)
  BYTES_PER_SEC_SI = 'Bps', // bytes/sec(SI)
  BITS_PER_SEC_IEC = 'binbps', // bits/sec(IEC)
  BITS_PER_SEC_SI = 'bps', // bits/sec(SI)
  KIBS = 'KiBs', // kibibytes/sec
  KIBITS = 'Kibits', // kibibits/sec
  KBS = 'KBs', // kilobytes/sec
  KBITS = 'Kbits', // kilobits/sec
  MIBS = 'MiBs', // mebibytes/sec
  MIBITS = 'Mibits', // mebibits/sec
  MBS = 'MBs', // megabytes/sec
  MBITS = 'Mbits', // megabits/sec
  GIBS = 'GiBs', // gibibytes/sec
  GIBITS = 'Gibits', // gibibits/sec
  GBS = 'GBs', // gigabytes/sec
  GBITS = 'Gbits', // gigabits/sec
  TIBS = 'TiBs', // tebibytes/sec
  TIBITS = 'Tibits', // tebibits/sec
  TBS = 'TBs', // terabytes/sec
  TBITS = 'Tbits', // terabits/sec
  PIBS = 'PiBs', // pebibytes/sec
  PIBITS = 'Pibits', // pebibits/sec
  PBS = 'PBs', // petabytes/sec
  PBITS = 'Pbits', // petabits/sec
  DATETIMEASISO = 'dateTimeAsIso', // Datetime ISO
  DATETIMEASISONODATEIFTODAY = 'dateTimeAsIsoNoDateIfToday', // Datetime ISO (No date if today)
  DATETIMEASUS = 'dateTimeAsUS', // Datetime US
  DATETIMEASUSNODATEIFTODAY = 'dateTimeAsUSNoDateIfToday', // Datetime US (No date if today)
  DATETIMEASLOCAL = 'dateTimeAsLocal', // Datetime local
  DATETIMEASLOCALNODATEIFTODAY = 'dateTimeAsLocalNoDateIfToday', // Datetime local (No date if today)
  DATETIMEASSYSTEM = 'dateTimeAsSystem', // Datetime default
  DATETIMEFROMNOW = 'dateTimeFromNow', // From Now
  WATT = 'watt', // Watt (W)
  KWATT = 'kwatt', // Kilowatt (kW)
  MEGWATT = 'megwatt', // Megawatt (MW)
  GWATT = 'gwatt', // Gigawatt (GW)
  MWATT = 'mwatt', // Milliwatt (mW)
  WM2 = 'Wm2', // Watt per square meter (W/m²)
  VOLTAMP = 'voltamp', // Volt-Ampere (VA)
  KVOLTAMP = 'kvoltamp', // Kilovolt-Ampere (kVA)
  VOLTAMPREACT = 'voltampreact', // Volt-Ampere reactive (VAr)
  KVOLTAMPREACT = 'kvoltampreact', // Kilovolt-Ampere reactive (kVAr)
  WATTH = 'watth', // Watt-hour (Wh)
  WATTHPERKG = 'watthperkg', // Watt-hour per Kilogram (Wh/kg)
  KWATTH = 'kwatth', // Kilowatt-hour (kWh)
  KWATTM = 'kwattm', // Kilowatt-min (kWm)
  MWATTH = 'mwatth', // Megawatt-hour (MWh)
  AMPH = 'amph', // Ampere-hour (Ah)
  KAMPH = 'kamph', // Kiloampere-hour (kAh)
  MAMPH = 'mamph', // Milliampere-hour (mAh)
  JOULE = 'joule', // Joule (J)
  EV = 'ev', // Electron volt (eV)
  AMP = 'amp', // Ampere (A)
  KAMP = 'kamp', // Kiloampere (kA)
  MAMP = 'mamp', // Milliampere (mA)
  VOLT = 'volt', // Volt (V)
  KVOLT = 'kvolt', // Kilovolt (kV)
  MVOLT = 'mvolt', // Millivolt (mV)
  DBM = 'dBm', // Decibel-milliwatt (dBm)
  MILLIOHM = 'mohm', // Milliohm (mΩ)
  OHM = 'ohm', // Ohm (Ω)
  KOHM = 'kohm', // Kiloohm (kΩ)
  MEGAOHM = 'Mohm', // Megaohm (MΩ)
  FARAD = 'farad', // Farad (F)
  UFARAD = 'µfarad', // Microfarad (µF)
  NFARAD = 'nfarad', // Nanofarad (nF)
  PFARAD = 'pfarad', // Picofarad (pF)
  FFARAD = 'ffarad', // Femtofarad (fF)
  HENRY = 'henry', // Henry (H)
  MHENRY = 'mhenry', // Millihenry (mH)
  UHENRY = 'µhenry', // Microhenry (µH)
  LUMENS = 'lumens', // Lumens (Lm)
  FLOWGPM = 'flowgpm', // Gallons/min (gpm)
  FLOWCMS = 'flowcms', // Cubic meters/sec (cms)
  FLOWCFS = 'flowcfs', // Cubic feet/sec (cfs)
  FLOWCFM = 'flowcfm', // Cubic feet/min (cfm)
  LITREH = 'litreh', // Litre/hour
  FLOWLPM = 'flowlpm', // Litre/min (L/min)
  FLOWMLPM = 'flowmlpm', // milliLitre/min (mL/min)
  LUX = 'lux', // Lux (lx)
  FORCENM = 'forceNm', // Newton-meters (Nm)
  FORCEKNM = 'forcekNm', // Kilonewton-meters (kNm)
  FORCEN = 'forceN', // Newtons (N)
  FORCEKN = 'forcekN', // Kilonewtons (kN)
  HS = 'Hs', // hashes/sec
  KHS = 'KHs', // kilohashes/sec
  MHS = 'MHs', // megahashes/sec
  GHS = 'GHs', // gigahashes/sec
  THS = 'THs', // terahashes/sec
  PHS = 'PHs', // petahashes/sec
  EHS = 'EHs', // exahashes/sec
  MASSMG = 'massmg', // milligram (mg)
  MASSG = 'massg', // gram (g)
  MASSLB = 'masslb', // pound (lb)
  MASSKG = 'masskg', // kilogram (kg)
  MASST = 'masst', // metric ton (t)
  LENGTHMM = 'lengthmm', // millimeter (mm)
  LENGTHIN = 'lengthin', // inch (in)
  LENGTHFT = 'lengthft', // feet (ft)
  LENGTHM = 'lengthm', // meter (m)
  LENGTHKM = 'lengthkm', // kilometer (km)
  LENGTHMI = 'lengthmi', // mile (mi)
  PRESSUREMBAR = 'pressurembar', // Millibars
  PRESSUREBAR = 'pressurebar', // Bars
  PRESSUREKBAR = 'pressurekbar', // Kilobars
  PRESSUREPA = 'pressurepa', // Pascals
  PRESSUREHPA = 'pressurehpa', // Hectopascals
  PRESSUREKPA = 'pressurekpa', // Kilopascals
  PRESSUREHG = 'pressurehg', // Inches of mercury
  PRESSUREPSI = 'pressurepsi', // PSI
  RADBQ = 'radbq', // Becquerel (Bq)
  RADCI = 'radci', // curie (Ci)
  RADGY = 'radgy', // Gray (Gy)
  RADRAD = 'radrad', // rad
  RADSV = 'radsv', // Sievert (Sv)
  RADMSV = 'radmsv', // milliSievert (mSv)
  RADUSV = 'radusv', // microSievert (µSv)
  RADREM = 'radrem', // rem
  RADEXPCKG = 'radexpckg', // Exposure (C/kg)
  RADR = 'radr', // roentgen (R)
  RADSVH = 'radsvh', // Sievert/hour (Sv/h)
  RADMSVH = 'radmsvh', // milliSievert/hour (mSv/h)
  RADUSVH = 'radusvh', // microSievert/hour (µSv/h)
  ROTRPM = 'rotrpm', // Revolutions per minute (rpm)
  ROTHZ = 'rothz', // Hertz (Hz)
  ROTKHZ = 'rotkhz', // Kilohertz (kHz)
  ROTMHZ = 'rotmhz', // Megahertz (MHz)
  ROTGHZ = 'rotghz', // Gigahertz (GHz)
  ROTRADS = 'rotrads', // Radians per second (rad/s)
  ROTDEGS = 'rotdegs', // Degrees per second (°/s)
  CELSIUS = 'celsius', // Celsius (°C)
  FAHRENHEIT = 'fahrenheit', // Fahrenheit (°F)
  KELVIN = 'kelvin', // Kelvin (K)
  HERTZ = 'hertz', // Hertz (1/s)
  NANOSECONDS = 'ns', // nanoseconds (ns)
  MICROSECONDS = 'µs', // microseconds (µs)
  MILLISECONDS = 'ms', // milliseconds (ms)
  SECONDS = 's', // seconds (s)
  MINUTES = 'm', // minutes (m)
  HOURS = 'h', // hours (h)
  DAYS = 'd', // days (d)
  DTDURATIONMS = 'dtdurationms', // duration (ms)
  DTDURATIONS = 'dtdurations', // duration (s)
  DTHMS = 'dthms', // duration (hh:mm:ss)
  DTDHMS = 'dtdhms', // duration (d hh:mm:ss)
  TIMETICKS = 'timeticks', // Timeticks (s/100)
  CLOCKMS = 'clockms', // clock (ms)
  CLOCKS = 'clocks', // clock (s)
  CPS = 'cps', // counts/sec (cps)
  OPS = 'ops', // ops/sec (ops)
  REQPS = 'reqps', // requests/sec (rps)
  RPS = 'rps', // reads/sec (rps)
  WPS = 'wps', // writes/sec (wps)
  IOPS = 'iops', // I/O ops/sec (iops)
  EPS = 'eps', // events/sec (eps)
  MPS = 'mps', // messages/sec (mps)
  RECPS = 'recps', // records/sec (rps)
  ROWSPS = 'rowsps', // rows/sec (rps)
  CPM = 'cpm', // counts/min (cpm)
  OPM = 'opm', // ops/min (opm)
  REQPM = 'reqpm', // requests/min (rpm)
  RPM = 'rpm', // reads/min (rpm)
  WPM = 'wpm', // writes/min (wpm)
  EPM = 'epm', // events/min (epm)
  MPM = 'mpm', // messages/min (mpm)
  RECPM = 'recpm', // records/min (rpm)
  ROWSPM = 'rowspm', // rows/min (rpm)
  VELOCITYMS = 'velocityms', // meters/second (m/s)
  VELOCITYKMH = 'velocitykmh', // kilometers/hour (km/h)
  VELOCITYMPH = 'velocitymph', // miles/hour (mph)
  VELOCITYKNOT = 'velocityknot', // knot (kn)
  MLITRE = 'mlitre', // millilitre (mL)
  LITRE = 'litre', // litre (L)
  M3 = 'm3', // cubic meter
  NM3 = 'Nm3', // Normal cubic meter
  DM3 = 'dm3', // cubic decimeter
  GALLONS = 'gallons', // gallons
  BOOL = 'bool', // True / False
  BOOL_YES_NO = 'bool_yes_no', // Yes / No
  BOOL_ON_OFF = 'bool_on_off', // On / Off
}
